SiteManagementWebApp/SiteManagement/Controllers/ResidentController.cs
using Microsoft.AspNetCore.Mvc;
using SiteManagement.Models.Db;
using SiteManagement.Models.Db.Entities;
using SiteManagement.Models.DTOs;
using SiteManagement.Services;
using System;
using System.Linq;

namespace SiteManagement.Controllers
{
    public class ResidentController : Controller
    {
        readonly ResidentService _residentService;
        readonly ApartmentService _apartmentService;

        public ResidentController(ResidentService residentService, ApartmentService service)
        {
            _residentService = residentService;
            _apartmentService = service;
        }

        [Route("resident/residentlist/{apartmentId}")]
        public IActionResult ResidentList(int apartmentId)
        {
            using (var context = new SiteManagementDbContext())
            {
                ViewBag.ResidentList = context.Humans.Where(h => h.ApartmentId == apartmentId).ToList();
                ViewBag.Apartment = context.Apartments.Where(a => a.Id == apartmentId).FirstOrDefault();
            }
            return View();
        }

        [Route("resident/createperson/{apartmentId}")]
        public IActionResult CreatePerson(int apartmentId)
        {
            ViewBag.ApartmentId = apartmentId;
            return View();
        }

        [HttpPost]
        [Route("resident/createperson/{apartmentId}")]
        public IActionResult CreatePerson(CreatePersonDTO createPersonDTO)
        {
            int apartmentId = Convert.ToInt32(HttpContext.Request.Path.Value.Split("/").LastOrDefault());
            Human newPerson = _residentService.CreatePerson(createPersonDTO, apartmentId);

            return RedirectToAction("ResidentList", new { apartmentId = newPerson.ApartmentId });
        }

        [HttpPost]
        public IActionResult DeletePerson(int personId)
        {
            _residentService.DeletePerson(personId);
            return Ok();
        }

        [Route("resident/updateperson/{apartmentId}/{personId}")]
        public IActionResult UpdatePerson(int apartmentId, int personId)
        {
            return View(_residentService.GetPersonByPersonIdandApartmentId(apartmentId, personId));
        }

        [Route("resident/updateperson/{apartmentId}/{personId}")]
        [HttpPost]
        public IActionResult UpdatePerson(UpdatePersonDTO updatePersonDTO)
        {
            Human toBeUpdatedPerson = _residentService.UpdatePerson(updatePersonDTO);
            return RedirectToAction("residentlist", new { apartmentId = toBeUpdatedPerson.ApartmentId });
        }

        [Route("resident/sethomeowner/{apartmentId}")]
        public IActionResult SetHomeOwner(int apartmentId)
        {
            ViewBag.ResidentList = _residentService.GetHomeOwnerById(apartmentId);
            return View();
        }

        [HttpPost]
        public IActionResult SetHomeOwnerPost(int responsible, int apartmentID)
        {
            _residentService.SetHomeOwner(responsible, apartmentID);
            return RedirectToAction("residentlist", new { apartmentId = apartmentID }); //Ajax succes data bekliyor, burayı ezer.
        }
    }
}

SiteManagementWebApp/SiteManagement/Views/Resident/CreatePerson.cshtml
@model SiteManagement.Models.DTOs.CreatePersonDTO;

<style>
    #position {
        position: absolute;
        left: 28%;
        top: 10%;
    }
</style>

<br />
<div style="width:40%;" id="position">
    <form class="avarage" asp-action="CreatePerson" asp-controller="Resident" method="post">
        <h5>Kişi ekleyin</h5> <br />
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Kişi adı ve soyadı" asp-for="NameSurname">
            <label for="floatingInput">Kişi adı ve soyadı</label>
        </div>
        <button type="submit" class="btn btn-outline-primary" style="width:25rem; position:absolute; right:2%;">Ekle</button> <br /> <br />
        <h6>Vazmı geçtiniz <a href="https://localhost:44309/resident/residentlist/@ViewBag.ApartmentId">geri dönün</a> </h6>
    </form>
</div>

SiteManagementWebApp/SiteManagement/Views/Resident/ResidentList.cshtml
@using SiteManagement.Models.Db.Entities;
@{
    var apartment = ViewBag.Apartment as Apartment;
}

<style>
    .ul {
        float: left;
        width: 40%;
        margin: 10px;
        position: absolute;
        top: 15%;
        left: 29%;
    }
    .btn1 {
        float: right;
        margin: 5px;
    }
</style>

<a style="float:right; margin:10px;" href="https://localhost:44309/resident/createperson/@apartment.Id"><button type="button" class="btn btn-success">Kişi Ekle</button></a>
<a style="float:right; margin:10px;" href="https://localhost:44309/resident/sethomeowner/@apartment.Id"><button type="button" class="btn btn-success">Daire Sorumlusu</button></a> <br />
<h4 style="position:absolute;left:29.5%; top:10%; color:#11033F;">@apartment.Name Oturanlar Listesi</h4>

<div class="ul">
    <ul class="list-group ">
        @foreach (var item in ViewBag.ResidentList)
        {
            <li class="list-group-item ">
                @item.NameSurname

                <button id="Delete_@item.Id" type="button" class="btn btn-outline-danger btn1" onclick="deletePerson(@item.Id)">Sil</button>
                <a href="https://localhost:44309/resident/updateperson/@apartment.Id/@item.Id"><button type="button" class="btn btn-outline-warning btn1">Düzenle</button></a>
            </li>
        }
    </ul>
</div>

<script type="text/javascript">
    function deletePerson(personId) {
        Swal.fire({
            title: 'Silmek istediğine emin misin?',
            text: " ",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Evet'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax(
                    {
                        type: "post",
                        url: '@Url.Action("DeletePerson", "Resident")',
                        data: { personId: personId },
                        success: function (data) {
                            Swal.fire({
                                title: 'Silindi!',
                                text: 'Daire silme işlemi başarı ile tamamlandı.',
                                showConfirmButton: false
                            }
                            )
                            setTimeout(function () {
                                window.location.reload(false)
                            }, 2000);
                        },
                        error: function () {
                            alert("Hata");
                        }
                    });
            }
        })
    }
</script>

SiteManagementWebApp/SiteManagement/Views/Resident/SetHomeOwner.cshtml
<style>
    #position {
        position: absolute;
        left: 28%;
        top: 10%;
    }
</style>
<br />
<div style="width:40%;" id="position">
        <h5>Daire sorumlusunu belirleyin</h5> <br />
        <select class="form-select" id="Responsible">
            <option selected>Daire Sorumlusu Seçin</option>
            @foreach (var item in ViewBag.ResidentList)
            {
                <option id="Owner_" value="@item.Id">@item.NameSurname</option>
            }
        </select>
        <br />
        <button type="submit" onclick="setOwner()" class="btn btn-outline-primary" style="width:25rem; position:absolute; right:2%;">Kaydet</button> <br /> <br />
        <h6>Vazmı geçtiniz <a href="#">geri dönün</a> </h6>
</div>
<script type="text/javascript">
    function setOwner() {
        var responsible = $('#Responsible').val();
        apartmentId = window.location.href.split('/').slice(-1);
        $.ajax({
            type: "POST",
            url: '@Url.Action("SetHomeOwnerPost", "Resident")',
            data: { responsible: responsible, apartmentId: apartmentId }, //Current url, slice(-1) = Url'in sonunu kestik.
            success: function (data) {
                window.location.href = 'https://localhost:44309/resident/residentlist/'+apartmentId;
            },
            error: function (data) {
                // Stuff
            }
        });
    }
</script>

SiteManagementWebApp/SiteManagement/Views/Resident/UpdatePerson.cshtml
@model SiteManagement.Models.DTOs.UpdatePersonDTO;

<style>
    #position {
        position: absolute;
        left: 28%;
        top: 10%;
    }
</style>

<br />
<div style="width:40%;" id="position">
    <form class="avarage" asp-action="UpdatePerson" asp-controller="Resident" method="post">
        <h5>Düzenleyin</h5> <br />
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Kişi adı ve soyadı" asp-for="NameSurname">
            <label for="floatingInput">Kişi adı ve soyadı</label>
        </div>
        <button type="submit" class="btn btn-outline-primary" style="width:25rem; position:absolute; right:2%;">Düzenle</button> <br /> <br />
        <h6>Vazmı geçtiniz <a href="https://localhost:44309/management/sitelist">geri dönün</a> </h6>
    </form>
</div>