SiteManagementWebApp/SiteManagement/Models/Db/Entities/Apartment.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SiteManagement.Models.Db.Entities
{
    public class Apartment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int BlockId { get; set; }
        public int? HomeOwnerId { get; set; }
        public ICollection<ApartmentDept> ApartmentDepts { get; set; }
        public ICollection<Human> Humans { get; set; }

        [ForeignKey(nameof(HomeOwnerId))]
        public Human Human { get; set; }


    }
}

SiteManagementWebApp/SiteManagement/Controllers/ApartmentController.cs
using Microsoft.AspNetCore.Mvc;
using SiteManagement.Models.Db.Entities;
using SiteManagement.Models.DTOs;
using SiteManagement.Services;
using System;
using System.Linq;

namespace SiteManagement.Controllers
{
    public class ApartmentController : Controller
    {
        readonly BlockService _blockService;
        readonly ApartmentService _apartmentService;
        public ApartmentController(BlockService blockService, ApartmentService apartmentService)
        {
            _blockService = blockService;
            _apartmentService = apartmentService;
        }

        [Route("apartment/list/{blockId}")]
        public IActionResult List(int blockId)
        {
            ViewBag.Block = _blockService.GetBlockWithApartmentByBlockId(blockId);
            return View();
        }

        [Route("apartment/createapartment/{blockId}")]
        public IActionResult CreateApartment(int blockId)
        {
            ViewBag.BlockId = blockId;
            return View();
        }

        [Route("apartment/createapartment/{blockId}")]
        [HttpPost]
        public IActionResult CreateApartment(CreateApartmentDTO createApartmentDTO)
        {
            int blockId = Convert.ToInt32(HttpContext.Request.Path.Value.Split('/').LastOrDefault());
            Apartment apartment = _apartmentService.CreateApartment(createApartmentDTO, blockId);
            return RedirectToAction("list", new { blockId = apartment.BlockId });
        }

        [HttpPost]
        public IActionResult DeleteApartment(int apartmentId)
        {
            _apartmentService.DeleteApartment(apartmentId);
            return Ok();
        }

        [Route("apartment/updateapartment/{blockId}/{apartmentId}")]
        public IActionResult UpdateApartment(int blockId, int apartmentId)
        {
            return View(_apartmentService.GetApartmentByBlockIdandApartmentId(blockId, apartmentId));
        }

        [Route("apartment/updateapartment/{blockId}/{apartmentId}")]
        [HttpPost]
        public IActionResult UpdateApartment(UpdateApartmentDTO updateApartmentDTO)
        {
            Apartment toBeUpdatedApartment = _apartmentService.UpdateApartment(updateApartmentDTO);
            return RedirectToAction("list", new { blockId = toBeUpdatedApartment.BlockId });
        }
    }
}

SiteManagementWebApp/SiteManagement/Views/Apartment/CreateApartment.cshtml
@using SiteManagement.Models.DTOs;
@model CreateApartmentDTO;

<style>
    #position {
        position: absolute;
        left: 28%;
        top: 10%;
    }

</style>

<br />
<div style="width:40%;" id="position">
    <form class="avarage" asp-action="CreateApartment" asp-controller="Apartment" method="post">
        <h5>Daire ekleyin</h5> <br />
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Daire adı" asp-for="Name">
            <label for="floatingInput">Daire adı</label>
        </div>
        <button type="submit" class="btn btn-outline-primary" style="width:25rem; position:absolute; right:2%;">Ekle</button> <br /> <br />
        <h6>Vazmı geçtiniz <a href="https://localhost:44309/apartment/list/@ViewBag.BlockId">geri dönün</a> </h6>
    </form>
</div>

SiteManagementWebApp/SiteManagement/Views/Apartment/List.cshtml
@using SiteManagement.Models.Db.Entities
@{
    var block = ViewBag.block as Block;
}

<style>
    .ul {
        float: left;
        width: 40%;
        margin: 10px;
        position: absolute;
        top: 15%;
        left: 29%;
    }

    .btn1 {
        float: right;
        margin: 5px;
    }

</style>

<a style="float:right; margin:10px;" href="https://localhost:44309/apartment/createapartment/@block.Id"><button type="button" class="btn btn-success">Daire Ekle</button></a> <br />
<h4 style="position:absolute;left:29.5%; top:10%; color:#11033F;">@block.BlockName Bloğu Daireleri</h4>

<div class="ul">
    <ul class="list-group ">
        @foreach (var item in block.Apartments)
        {
            <li class="list-group-item ">
                @item.Name
                
                <button id="Delete_@item.Id" type="button" class="btn btn-outline-danger btn1" onclick="deleteApartment(@item.Id)">Sil</button>
                <a href="https://localhost:44309/apartment/updateapartment/@block.Id/@item.Id"><button type="button" class="btn btn-outline-warning btn1">Düzenle</button></a>
                <a href="https://localhost:44309/resident/residentlist/@item.Id"><button type="button" class="btn btn-outline-success btn1">Yaşayanlar</button></a>
                @if (block != null)
                {
                    @foreach (var item2 in block.Apartments)
                    {
                        @if (item2.HomeOwnerId != null && item == item2)
                        {
                            <p style="color:dodgerblue;"><strong>Daire Sorumlusu:  </strong>@item2.Human.NameSurname </p>
                        }
                    }
                }
            </li>
        }
    </ul>
</div>

<script type="text/javascript">
    function deleteApartment(apartmentId) {
        Swal.fire({
            title: 'Silmek istediğine emin misin?',
            text: " ",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Evet'
        }).then((result) => {
            if (result.isConfirmed) {

                $.ajax(
                    {
                        type: "post",
                        url: '@Url.Action("DeleteApartment", "Apartment")',
                        data: { apartmentId: apartmentId },
                        success: function (data) {

                            Swal.fire({
                                title: 'Silindi!',
                                text: 'Daire silme işlemi başarı ile tamamlandı.',
                                showConfirmButton: false
                            }
                            )
                            setTimeout(function () {
                                window.location.reload(false)
                            }, 2000);
                        },
                        error: function () {
                            alert("Hata");
                        }
                    });
            }
        })
    }
</script>

SiteManagementWebApp/SiteManagement/Views/Apartment/UpdateApartment.cshtml
@model SiteManagement.Models.DTOs.UpdateApartmentDTO;

<style>
    #position {
        position: absolute;
        left: 28%;
        top: 10%;
    }
</style>

<br />
<div style="width:40%;" id="position">
    <form class="avarage" asp-action="UpdateApartment" asp-controller="Apartment" method="post">
        <h5>Düzenleyin</h5> <br />
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Daire adı" asp-for="ApartmentName">
            <label for="floatingInput">Daire adı</label>
        </div>
        <button type="submit" class="btn btn-outline-primary" style="width:25rem; position:absolute; right:2%;">Düzenle</button> <br /> <br />
        <h6>Vazmı geçtiniz <a href="https://localhost:44309/management/sitelist">geri dönün</a> </h6>
    </form>
</div>