SiteManagementWebApp/SiteManagement/Controllers/ManagementController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SiteManagement.Models.Db;
using SiteManagement.Models.DTOs;
using SiteManagement.Services;

namespace SiteManagement.Controllers
{
    public class ManagementController : Controller
    {
        readonly SiteManagementDbContext _context;
        readonly SiteService _siteService;
        readonly CommonService _commonService;

        public ManagementController(SiteManagementDbContext context, SiteService siteService, CommonService commonService)
        {
            _context = context;
            _siteService = siteService;
            _commonService = commonService;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                return View();
            }
            return RedirectToAction("Login", "Auth");
        }

        public IActionResult SiteList()
        {
            ViewBag.SiteList = _siteService.GetSiteListOrdered();
            return View();
        }

        public IActionResult CreateNewSite()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateNewSite(CreateSiteDTO createSiteDTO)
        {
            _siteService.CreateNewSite(createSiteDTO);
            return RedirectToAction("SiteList");
        }

        public IActionResult UpdateSite(int id)
        {
            return View(_siteService.GetSiteById(id));
        }

        [HttpPost]
        public IActionResult UpdateSite(UpdateSiteDTO updateSiteDTO)
        {
            _siteService.UpdateSite(updateSiteDTO);
            return RedirectToAction("SiteList");
        }

        [HttpPost]
        public IActionResult DeleteSite(int siteId)
        {
            _siteService.DeleteSite(siteId);
            return Ok();
        }

        public IActionResult GetDistricts(int cityId)
        {
                return Json(_commonService.GetDistrictListByCityId(cityId));
        }

        public IActionResult GetCities()
        {
                return Json(_commonService.GetCities());
        }
    }
}

SiteManagementWebApp/SiteManagement/Views/Management/CreateNewSite.cshtml
@model SiteManagement.Models.DTOs.CreateSiteDTO;

<style>
    #position {
        position: absolute;
        left: 28%;
        top: 10%;
    }
</style>

<br />
<div style="width:40%;" id="position">
    <form class="avarage" asp-action="CreateNewSite" asp-controller="Management" method="post">

        <h5>Site oluşturun</h5> <br />
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Site adı" asp-for="Name">
            <label for="floatingInput">Site Adı</label>
        </div>

        <script type="text/javascript">
            $(document).ready(function () {
                $.ajax(
                    {
                        type: "post",
                        url: '@Url.Action("GetCities", "Management")',
                        success: function (cities) {
                            $.each(cities, function (index, city) {
                                $('#Cities').append($('<option/>',
                                    {
                                        value: city.id,
                                        text: city.name
                                    }));
                            }
                            );
                        },
                        error: function () {
                            /*Bu metod ile Ajax işlemi başarısız
                            olursa eğer hata mesajı verebiliyoruz.*/
                            alert("Hata");
                        }
                    });

                // Kategori seçildiğinde bu fonksiyonumuz çalışmaya başlayacaktır.
                $('#Cities').change(function () {
                    // Seçilen Kategorinin ID sini alıyoruz.
                    var cityId = $(this).val();
                    /*Seçilen KategoriID sini kullanarak
                    Kategori(Controller) sınıfı içerisindeki AltKategorileriGetir
                    Action metodunu çağırıyoruz.
                    Bu metoddan dönen liste sayesinde .each fonksiyonu ile
                    AltKategori isimli DropDownList nesnesini dolduruyoruz.*/
                    if (cityId != null && cityId != '') {
                        $.ajax({
                            type: "post",
                            url: '@Url.Action("GetDistricts", "Management")',
                            data: { cityId: cityId },
                            success: function (districts) {

                                $('#Districts').find('option').remove().end().append('<option selected="selected">İlçe Seçin</option>');

                                $.each(districts, function (index, district) {
                                    $('#Districts').append($('<option/>', {
                                        value: district.id,
                                        text: district.name
                                    }));
                                });
                            },
                            error: function () {
                                /*Bu metod ile Ajax işlemi başarısız
                                olursa eğer hata mesajı verebiliyoruz.*/
                                alert("Hata");
                            }
                        });
                    }
                });
            });
        </script>

        <select class="form-select" id="Cities">
            <option selected>Şehir Seçin</option>
        </select>
        <br />
        <select class="form-select" id="Districts" asp-for="DistrictId">
            <option selected>İlçe Seçin</option>
        </select>
        <br />

        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingInput" placeholder="Adres" asp-for="Adress">
            <label for="floatingInput">Site Adresi</label>

        </div> <br />

        <button type="submit" class="btn btn-outline-primary" style="width:25rem; position:absolute; right:2%;">Oluştur</button> <br /> <br />
        <h6>Vazmı geçtiniz <a href="https://localhost:44309/management/sitelist">geri dönün</a> </h6>
    </form>
</div>

SiteManagementWebApp/SiteManagement/Views/Management/Index.cshtml
<strong>Mevcut siteleri görmek için tıkla.</strong> <a href="http://localhost:44309/management/sitelist">tıkla.</a>

SiteManagementWebApp/SiteManagement/Views/Management/SiteList.cshtml
<style>
    .ul {
        float: left;
        width: 40%;
        margin: 10px;
        position: absolute;
        top: 15%;
        left: 29%;
    }

    .btn1 {
        float: right;
        margin: 5px;
    }

</style>

<a style="float:right; margin:10px;" href="https://localhost:44309/management/createnewsite"><button type="button" class="btn btn-success">Site Oluştur</button></a> <br />

<h4 style="position:absolute;left:29.5%; top:10%; color:#11033F;">Siteler</h4>
<div class="ul">
    <ul class="list-group ">
        @foreach (var item in ViewBag.SiteList)
        {
            <li class="list-group-item ">
                @item.Name

                <button id="Delete_@item.Id" type="button" class="btn btn-outline-danger btn1" onclick="DeleteSite(@item.Id)">
                    Sil
                </button>
                <a href="https://localhost:44309/management/UpdateSite/@item.Id"><button type="button" class="btn btn-outline-warning btn1">Düzenle </button></a>
                <a href="https://localhost:44309/block/list/@item.Id"><button type="button" class="btn btn-outline-success btn1">Bloklar</button></a>
                <a href="https://localhost:44309/worker/workerlist/@item.Id"><button type="button" class="btn btn-outline-secondary btn1">Görevliler</button></a>
            </li>
        }
    </ul>
</div>

<script type="text/javascript">
    function DeleteSite(siteId) {
        Swal.fire({
            title: 'Silmek istediğine emin misin?',
            text: " ",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Evet'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax(
                    {
                        type: "post",
                        url: '@Url.Action("DeleteSite", "Management")',
                        data: { siteId: siteId },
                        success: function (data) {
                            Swal.fire(
                                'Silindi!',
                                'Site silme işlemi başarı ile tamamlandı.'
                            )
                            setTimeout(function () {
                                window.location.href = "sitelist"
                            }, 1000);
                        },
                        error: function () {
                            alert("Hata");
                        }
                    });
            }
        })
    }
</script>

SiteManagementWebApp/SiteManagement/Views/Management/UpdateSite.cshtml
@model SiteManagement.Models.DTOs.UpdateSiteDTO;

<style>
    #position {
        position: absolute;
        left: 28%;
        top: 10%;
    }

</style>
<br />
<div style="width:40%;" id="position">
    <form class="avarage" asp-action="UpdateSite" asp-controller="Management" method="post">

        <h5>Siteyi düzenleyin</h5> <br />
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Site adı" asp-for="SiteName">
            <label for="floatingInput">Site Adı</label>

        </div>
        
        <select class="form-select" id="Cities">
        </select>
        <br />
        <select class="form-select" id="Districts" asp-for="DistrictId">
        </select>
        <br />

        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingInput" placeholder="Adres" asp-for="SiteAdress">
            <label for="floatingInput">Site Adresi</label>

        </div> <br />

        <button type="submit" class="btn btn-outline-primary" style="width:25rem; position:absolute; right:2%;">Düzenle</button> <br /> <br />
        <h6>Vazmı geçtiniz <a href="https://localhost:44309/yonetim">geri dönün</a> </h6>
    </form>
</div>


<script type="text/javascript">
    
    $(document).ready(function () {
        function getDistricts(cityId) {
            $.ajax({
                type: "post",
                url: '@Url.Action("GetDistricts", "Management")',
                data: { cityId: cityId },
                success: function (districts) {  //Backendden başarılı dönünce gelen Json
                    $('#Districts').find('option').remove().end();
                    $.each(districts, function (index, district) {
                        $('#Districts').append($('<option/>', {
                            id: "district_" + district.id,
                            value: district.id,
                            text: district.name
                        }));
                    });
                    $('#district_' + @Model.DistrictId).attr("selected", true); //Key = value
                },
                error: function () {
                    /*Bu metod ile Ajax işlemi başarısız
                    olursa eğer hata mesajı verebiliyoruz.*/
                    alert("Hata");
                }
            });
        }

        $.ajax(
            {
                type: "post",
                url: '@Url.Action("GetCities", "Management")',
                success: function (cities) {
                    $.each(cities, function (index, city) {
                        $('#Cities').append($('<option/>',
                            {
                                id: "city_" + city.id,
                                value: city.id,                       //Attributes
                                text: city.name
                            }));
                    }
                    );
                    $('#city_'+@Model.CityId).attr("selected", true); //Key = value
                    getDistricts(@Model.CityId);
                },
                error: function () {
                    /*Bu metod ile Ajax işlemi başarısız
                    olursa eğer hata mesajı verebiliyoruz.*/
                    alert("Hata");
                }
            });

        $('#Cities').change(function () {
            getDistricts($(this).val());
        });
    });
</script>