SiteManagementWebApp/SiteManagement/Models/Db/Entities/Worker.cs
namespace SiteManagement.Models.Db.Entities
{
    public class Worker
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public string NameSurname { get; set; }
        public string Duty { get; set; }
    }
}

SiteManagementWebApp/SiteManagement/Controllers/WorkerController.cs
using Microsoft.AspNetCore.Mvc;
using SiteManagement.Models.DTOs;
using SiteManagement.Services;
using System;
using System.Linq;

namespace SiteManagement.Controllers
{
    public class WorkerController : Controller
    {
        readonly WorkerService _workerService;
        readonly SiteService _siteService;

        public WorkerController(WorkerService workerService, SiteService siteService)
        {
            _workerService = workerService;
            _siteService = siteService;
        }

        [Route("worker/workerlist/{siteId}")]
        public IActionResult WorkerList(int siteId)
        {
            var site = _siteService.GetSiteWithWorkers(siteId);
            ViewBag.SiteName = site.Name;
            ViewBag.WorkerList = site.Workers.ToList();
            return View(siteId);
        }

        [Route("worker/deleteworker")]
        [HttpPost]
        public IActionResult DeleteWorker(int workerId)
        {
            _workerService.DeleteWorker(workerId);
            return Ok();
        }

        [Route("worker/createworker/{siteId}")]
        public IActionResult CreateWorker(int siteId)
        {
            ViewBag.SiteId = siteId;
            return View();
        }

        [Route("worker/createworker/{siteId}")]
        [HttpPost]
        public IActionResult CreateWorker(CreateWorkerDTO createWorkerDTO)
        {
            int siteId = Convert.ToInt32(HttpContext.Request.Path.Value.Split('/').LastOrDefault());
            _workerService.CreateWorker(createWorkerDTO, siteId);

            return RedirectToAction("workerlist", new { siteId = siteId });
        }

        [Route("worker/updateworker/{siteId}/{workerId}")]
        public IActionResult UpdateWorker(int siteId, int workerId)
        {
            return View(_workerService.WorkerToUpdate(siteId, workerId));
        }

        [HttpPost]
        [Route("worker/updateworker/{siteId}/{workerId}")]
        public IActionResult UpdateWorker(UpdateWorkerDTO updateWorkerDTO, int siteId)
        {
            _workerService.UpdateWorker(updateWorkerDTO);
            return RedirectToAction("workerlist", new { siteId = siteId }); 
        }
    }
}

SiteManagementWebApp/SiteManagement/Views/Worker/CreateWorker.cshtml
@model SiteManagement.Models.DTOs.CreateWorkerDTO;
<style>
    #position {
        position: absolute;
        left: 28%;
        top: 10%;
    }
</style>

<br />
<div style="width:40%;" id="position">
    <form class="avarage" asp-action="CreateWorker" asp-controller="Worker" method="post">
        <h5>Daire ekleyin</h5> <br />
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Görevli ismi" asp-for="NameSurname">
            <label for="floatingInput">Görevli ismi</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Görevi" asp-for="Duty">
            <label for="floatingInput">Görevi</label>
        </div>
        <button type="submit" class="btn btn-outline-primary" style="width:25rem; position:absolute; right:2%;">Ekle</button> <br /> <br />
        <h6>Vazmı geçtiniz <a href="https://localhost:44309/worker/workerlist/@ViewBag.siteId">geri dönün</a> </h6>
    </form>
</div>

SiteManagementWebApp/SiteManagement/Views/Worker/UpdateWorker.cshtml
@using SiteManagement.Models.DTOs;
@model UpdateWorkerDTO;
<style>
    #position {
        position: absolute;
        left: 28%;
        top: 10%;
    }
</style>

<br />
<div style="width:40%;" id="position">
    <form class="avarage" asp-action="UpdateWorker" asp-controller="Worker" method="post">
        <h5>Düzenleyin</h5> <br />
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Adı ve Soyadı" asp-for="NameSurname">
            <label for="floatingInput">Adı ve Soyadı</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" style="font-size:20px;" class="form-control" id="floatingInput" placeholder="Görevi" asp-for="Duty">
            <label for="floatingInput">Görevi</label>
        </div>
        <button type="submit" class="btn btn-outline-primary" style="width:25rem; position:absolute; right:2%;">Düzenle</button> <br /> <br />
        <h6>Vazmı geçtiniz <a href="https://localhost:44309/worker/workerlist/@Model.SiteId">geri dönün</a> </h6>
    </form>
</div>

SiteManagementWebApp/SiteManagement/Views/Worker/WorkerList.cshtml
@using SiteManagement.Models.Db.Entities;
@model int;
@{
    var workers = ViewBag.WorkerList as List<Worker>; //ViewBag.WorkerList = List olacak 

    var site = ViewBag.Site as Site;
}
<style>
    .ul {
        float: left;
        width: 40%;
        margin: 10px;
        position: absolute;
        top: 15%;
        left: 29%;
    }

    .btn1 {
        float: right;
        margin: 5px;
    }
</style>

<a style="float:right; margin:10px;" href="https://localhost:44309/worker/createworker/@Model"><button type="button" class="btn btn-success">Görevli Ekle</button></a> <br />

<h4 style="position:absolute;left:29.5%; top:10%; color:#11033F;">@ViewBag.SiteName Sitesi Görevlileri</h4>

<div class="ul">
    <ul class="list-group ">
        @foreach (var item in workers)  
        {
            <li class="list-group-item ">
                @item.NameSurname
                <button id="Delete_@item.Id" type="button" class="btn btn-outline-danger btn1" onclick="deleteWorker(@item.Id)">
                    Sil
                </button>

                <a href="https://localhost:44309/worker/updateworker/@Model/@item.Id"><button type="button" class="btn btn-outline-warning btn1">Düzenle </button></a>
                <p style="color:dodgerblue;"><strong>Görevi:  </strong>@item.Duty </p>
            </li>
        }
    </ul>
</div>

<script type="text/javascript">
    function deleteWorker(workerId) {
        Swal.fire({
            title: 'Silmek istediğine emin misin?',
            text: " ",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Evet'
        }).then((result) => {
            if (result.isConfirmed) {

                $.ajax(
                    {
                        type: "post",
                        url: '@Url.Action("DeleteWorker", "Worker")',
                        data: { workerId: workerId },
                        success: function (data) {

                            Swal.fire({
                                title: 'Silindi!',
                                text: 'Daire silme işlemi başarı ile tamamlandı.',
                                showConfirmButton: false
                            }
                            )
                            setTimeout(function () {
                                window.location.reload(false)
                            }, 2000);
                        },
                        error: function () {
                            alert("Hata");
                        }
                    });
            }
        })
    }
</script>